### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by xavierartot** [seothemes/genesis-starter-theme#28] opened 2019-02-01 06:36 UTC
I cloned the project and sh setup.sh
I have this error:

```
  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - authors[0].homepage : Invalid URL format
```
then

```[00:34:34] Starting 'browser-sync'...
[00:34:34] Finished 'browser-sync' after 7.66 ms
[00:34:34] Starting 'watch'...
[00:34:42] Finished 'watch' after 8.32 s
[00:34:42] Starting 'serve'...
[00:34:42] Finished 'serve' after 38 μs
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/seothemes/.valet/Certificates/xavierv.key'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at getKey (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/utils.js:38:15)
    at getHttpsServerDefaults (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/utils.js:45:14)
    at Object.getHttpsOptions (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/utils.js:67:41)
    at /Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/utils.js:81:44
    at Object.getServer (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/utils.js:85:15)
    at createProxyServer (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/proxy-server.js:87:35)
    at createServer (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/index.js:69:41)
    at module.exports.plugin (/Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis-starter-theme/node_modules/browser-sync/dist/server/index.js:12:20)
➜  genesis-starter-theme git:(master) ✗
```
Here my composer.json

```
➜  genesis-starter-theme git:(master) ✗ cat composer.json
{
  "name": "seothemes/xavierv",
  "type": "wordpress-theme",
  "description": "Genesis starter theme with a modern development workflow.",
  "keywords": [
    "WordPress",
    "wordpress-theme-development",
    "genesis-framework"
  ],
  "license": "GPL-3.0-or-later",
  "authors": [
    {
      "name": "Lee Anthony",
      "homepage": "xavierv",
      "role": "Developer"
    }
  ],
  "support": {
    "issues": "https://github.com/seothemes/xavierv/issues",
    "source": "https://github.com/seothemes/xavierv"
  },
  "require": {
    "php": ">=5.4",
    "seothemes/core": "dev-master",
    "tgmpa/tgm-plugin-activation": "dev-develop"
  },
  "require-dev": {},
  "autoload": {
    "psr-4": {
      "xavierv\\xavierv\\": "app/"
    }
  },
  "suggest": {},
  "config": {
    "sort-order": true
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
    "post-create-project-cmd": [
      "yarn install"
    ],
    "post-install-cmd": [
      "yarn install"
    ],
    "stylelint": [
      "stylelint './assets/scss/**/*.scss' --fix"
    ],
    "phpcs": [
      "phpcs"
    ]
  }
}
```

**Comment by seothemes** [comment] 2019-02-01 06:38
The second error is caused by the local certificate. You can use a non-secure site by removing the https settings in the Gulpfile.js

**Comment by xavierartot** [comment] 2019-02-01 07:03
I'm using MAMP
I don't have domain, I just trying this starter theme. 

gulpfile.js can minifiy the css and js, I don't see the tasks?
Do I have to change the proxy to my local server?
```    server: {
      proxy: 'https://xav',
      host: 'xav',
      open: 'external',
      port: '8000',
      //https: {
        //'key': '/Users/seothemes/.valet/Certificates/xav.key',
        //'cert': '/Users/seothemes/.valet/Certificates/xav.crt'
      //}
    }
```

**Comment by seothemes** [comment] 2019-02-02 01:06
Closing as this is not a theme issue. For support please visit [https://seothemes.com/support](https://seothemes.com/support)

**Closed by seothemes** 2019-02-02 01:06 UTC
